### PR TITLE
Fix highlighting errors over ssh

### PR DESCRIPTION
**Pull request by david-collingwood**
Thought I might just give this a go. I'm using the "hack_ssh_folder" value to turn hh_client's filename into a relative url. I'm not sure how bullet-proof this solution is, but it seemed to do the trick for me.

### CODE REVIEW

**Comment by SiebelsTim** [comment]
I like it! Hopefully I have enough time tonight to test it.

**Comment by david-collingwood** [comment]
I'm not sure whether this was something you were intending on implementing or not, but I found that if I had not previously spawned the hh_server, that upon saving, the application would hang while the server was being started. So I've just refactored the code a little bit to run "hh_client" in a separate thread. Let me know what you think :)

**Comment by SiebelsTim** [comment]
Yeah... I noticed this some time ago. I really really like having this asynchronous.

I just returned back home and I need a little time to touch up for some things. This will take a few days, sorry! I'll get to it asap.

**Comment by SiebelsTim** [comment]
Love it! merged it.

**Pull request closed without merging**
